project_id = "rbaifrcrscjpfnettvre"

[functions.create-payment]
verify_jwt = false

[functions.payfast-itn]
verify_jwt = false

[functions.generate-special-image]
verify_jwt = false

[functions.fetch-google-reviews]
verify_jwt = false
